/*
 */


import javax.swing.JOptionPane;
import javax.swing.JLabel;
import java.awt.Font;
import javax.swing.ImageIcon;
import java.awt.Color;
import java.awt.SystemColor;

/**
 *
 * @author DharshikaSingarathnam
 */
public class LoginForm extends javax.swing.JFrame {

    MonitorManager monitorManager;
    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        // Center the UI
        this.setLocationRelativeTo(null);
        monitorManager = new MonitorManager();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  
    private void initComponents() {

        username = new javax.swing.JTextField();
        username.setBackground(SystemColor.menu);
        jButton1 = new javax.swing.JButton();
        jButton1.setFont(new Font("Tahoma", Font.BOLD, 15));
        jButton1.setBackground(Color.WHITE);
        password = new javax.swing.JPasswordField();
        password.setBackground(SystemColor.menu);
       

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(204, 0, 204));
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(680, 360));
        setMinimumSize(new java.awt.Dimension(680, 360));
        setPreferredSize(new java.awt.Dimension(680, 360));
        setResizable(false);
        getContentPane().setLayout(null);
        getContentPane().add(username);
        username.setBounds(460, 176, 190, 26);

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(499, 250, 110, 40);
        getContentPane().add(password);
        password.setBounds(460, 213, 190, 26);
        
        JLabel lblUsername = new JLabel("Username");
        lblUsername.setForeground(Color.WHITE);
        lblUsername.setFont(new Font("Tahoma", Font.BOLD, 14));
        lblUsername.setBounds(360, 180, 100, 14);
        getContentPane().add(lblUsername);
        
        JLabel lblPassword = new JLabel("Password");
        lblPassword.setForeground(Color.WHITE);
        lblPassword.setFont(new Font("Tahoma", Font.BOLD, 14));
        lblPassword.setBounds(360, 217, 100, 14);
        getContentPane().add(lblPassword);
        
        JLabel label = new JLabel("");
        label.setIcon(new ImageIcon("C:\\Users\\Dell\\Desktop\\it16001244\\Assignment1\\src\\firealarm-750x562.jpg"));
        label.setBounds(0, 0, 674, 332);
        getContentPane().add(label);

       

        pack();
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//jButton1ActionPerformed
        if(LoginManager.authenticateUser(username.getText(),password.getText())){
            monitorManager.startMonitor();
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(
                                    null,
                                    "Failed to authenticate user! Please check username and password!",
                                    "AUTHENTICATION FAILED",
                                    JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
}
